tplProjectName: mobilebuilder_tpl_8_0_0_ngx
â†“FCMPushNotifications [ngx.components.UIActionStack-1591517891678]: ğŸ— mobileSharedActions/FCMPushNotifications.yaml
â†“DemoPage [ngx.components.PageComponent-1591517856447]: ğŸ— mobilePages/DemoPage.yaml